name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config libjson-c-dev

    - name: Build
      run: gcc $(pkg-config --cflags --libs json-c) -o fflag SoberFFlagEditor.c

    - name: Run fflag list (test)
      run: ./fflag list
