name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config libjson-c-dev

    - name: Compile with json-c
      run: |
        CFLAGS="$(pkg-config --cflags json-c)"
        LDFLAGS="$(pkg-config --libs json-c)"
        gcc $CFLAGS SoberFFlagEditor.c $LDFLAGS -o fflag

    - name: Run fflag list (basic test)
      run: ./fflag list
